In [2]:
import numpy as np
import pandas as pd
import sklearn as sk
import matplotlib.pyplot as plt
import scipy as sp
%matplotlib inline

In [3]:
out2 = pd.DataFrame({'orderid':[1953277092]*620947, 'is_fraud':['not fraud']*620947})
out2.to_csv('out2.csv', index=False)

In [4]:
orders = pd.read_csv('opn-rd2-acv/orders.csv')
orders

           orderid  buyer_userid  seller_userid
0       1953278092      47388162       20822974
1       1953295120      26855196       16416890
2       1953306402     121296714       28477978
3       1953314712     131221930       72837912
4       1953381964     183398314       28423332
5       1953383372      69247284       62795594
6       1953451192      89510674       18186196
7       1953453596     198638326        7314602
8       1953479046     202508756        1988634
9       1953480060     130236220       77145726
10      1953480556     124028334       88036266
11      1953499218     235370780       63314464
12      1953513980       6211008       48384126
13      1953537154     210510748       34245056
14      1953545166      22334478       20535640
15      1953546308      22763432       26484422
16      1953553940     233625552       33528048
17      1953562818      42637998       64717472
18      1953563400      84617054       54888040
19      1953563816      67093476       18186196
20      1953564670     119768822       63394232
21      1953567064     158115678      103582530
22      1953593908     106935036       58925456
23      1953599970      17430812      100833828
24      1953600366      83284680       47326438
25      1953615002       3086192       31144588
26      1953616744     133207632       22711828
27      1953625742     171946686       57752956
28      1953627158      86833134       34245056
29      1953640202      36481740       72188470
...            ...           ...            ...
620917  1956338070      44898310        5312508
620918  1956344618      39964384       95590768
620919  1956360076     155710618       99173850
620920  1956379034     134117712       36387050
620921  1956415556      12361456      193529670
620922  1956423470      36154014       18658058
620923  1956447730     195686900       23929342
620924  1956453994      82485352       40965448
620925  1956458000      39039498      121514782
620926  1956463002      72940098        3289956
620927  1956481946      18835000       63769666
620928  1956482726     134296548       23530950
620929  1956499166      81742130       26970898
620930  1956504154      76824054       45636364
620931  1956507366     187110728       32696558
620932  1956507668     212458370      144373320
620933  1956517796     131904496      128938986
620934  1956536964      10695666       98644750
620935  1956539600     233633064       37454884
620936  1956540600     233038900       22925258
620937  1956561772     158271248      128755420
620938  1956581580      11510108       18801988
620939  1956605830      77942738       32054290
620940  1956618660      49574940        5636122
620941  1956619858       2334822       98365418
620942  1956636054      14222102       70940136
620943  1956642760       2978154       60766142
620944  1956651496     221974772       15541938
620945  1956660812     152533590       80986700
620946  1956679514      54374608       10385548

[620947 rows x 3 columns]

In [5]:
out2['orderid'] = orders['orderid']
out2.to_csv('out2.csv', index=False)

In [6]:
devices = pd.read_csv('opn-rd2-acv/devices.csv')
devices

            userid                                        device
0         10499978  0Zu/mWZ4cFsvobYglgZEc5VSxwwajRwrm74pBuwnrTu=
1         54526742  zBMRKyz98iy5Z7sh+JIOdF612J1CB8ggvFBI6MP361q=
2         33152428  KXC0oY3MMrTG+bnlFFvBPXZC5PW8iw6kgWztENWdIJg=
3         55020986  anRXS7+zVgCGKz5C9X3dzewIhSdojGEi5TO07pb2y+K=
4        100471502  hbIARr+USwvjjzc8QUVtD5a/apR1DJX6P3fYvgDL4gW=
5         61471588  iVuRAqjJYPDrwq7W/OVP9EuiCLyPgOT9cv7ZmjDy4Gy=
6         62907954  Qy0OTEs+/dmv+aBN4Qw4mQScGsAAp435kHF69jdnQUm=
7         37491720  7IzAgA/z/+BpwyIwsGf4bfbUmZHpf+axxrM+ij8/FDg=
8         20756502  WdTSc6p/VKXhA6Hm+hwCk4xEmep7IiHC34sCIAf1oBW=
9        133160044  r7MzY5w6X7pz0kKqhAG4cIoU1CmcA/oG8BZ7CCBnK5E=
10       112533348  +KjaiJ6aL1A+AZ+iGK10fpnEK9NU1My/qnlA5CG4Qdc=
11        29345296  TGaB5cwOkWSi0YEvqhcZYyrUn1HAbi/Nj6gU3OmsCTO=
12        62003492  4bJgIFbzMZ3ywzrGdt5iGtkA3U8YxM/VmtEo9GMxxsm=
13       111158712  WCEQvMImKQ/H/IPXLLw7cT2HXV3aJVTeZVVgDjLPJrc=
14        49136406  Ps9ArbhXG1NFmtnRK2ABRkqEh0ySUAV4F+vj9NdD5xq=
15        15655730  d9xXgfi0k+LBkKpGjZ3wdoFUgzzbRgf16NfLgIKEm+W=
16        87708778  RR2bcCb5BejNmCE8mJkFKTTV6M6d2ssWyTmB2F5hqay=
17        26860728  L5vEz9kSJC3l7aG2C6fC0U+H9tKnrMooP7XXkyFvW4E=
18       124665716  m+NV3TUUdE/V2t+BZDSMNwzAHvx3SYusKoojhwvC/6S=
19       104362298  TkOilRyx0/KguYnfczy87wv1aam4GwZH9ngLcnYDJau=
20        77295640  oS5Q3qZ8g1fXYMSKTQvy8BlePxw0WnjJTXbtJ7lagUc=
21        42916456  PZY9g+HdVy0Yk8jF4YQKP8hRWK4GQynkW7FiOEgiW6I=
22       133432602  bqxLTPOvjnI6qrAFmOf5U/ZZFXAUYea+eV7W3sbi3pI=
23        85362946  CGpIYbM92ADLIaFsY4viy8Ck6bq2dLm9cPGS2+YSlQO=
24       133440156  g+M0b4cD+4d8XKJQTprQRWoUXsHJTJbtMNGiGTDT9bu=
25       129669524  pdYhqPS3cmuPC3pm8HUVWD41lCxQJtT8Q5OmVmZ2ply=
26        38318486  qro2+wUmlONNGm7pTP4SfUddmjJhgz4sXvpmrLh7Ap8=
27       100955932  qttUgkdfqqrLzqmJz4fYJbEgbIAyZABuSv8vUr/fL50=
28        88244914  k2SiGCPcKIBTrQdcIMfM4HU2EwE4+tuhoOSMsEmlqoW=
29        15190214  6xoWlzZrjCPxENoR9lXr09m+xNCxISXGiMJ6/GvNvnc=
...            ...                                           ...
1430281   70441986  q/uqu52fGCn4u/KgKN/oGq2KPSC5XxGeFSAXtOYboa8=
1430282   11897402  OrvQuNxbnKDLhGyUspFxAx/YSlqNZhJdwZLCtz9ZvF4=
1430283   12403226  MWsteZ6QkYf0tcywCF1h1jjBmKtlw8SG6+L04TicL5c=
1430284    5556248  nnan0cGgDjDUA5b0ESOx2sZbaZInndpLHKn86jjCkAE=
1430285   11859436  MCqjSPpSI4SBcmefKehnQtHJGBVlzGP7n+ZNPpV8GNq=
1430286    9044860  hNUB72NMpK9zM2hazjLYDzJtIsk9VLBJpoHxtyxPxJ8=
1430287   11812634  UFjiwYsuefUJtf6KhLSqmH8OnTcGQw2pDUjsUQO5CiA=
1430288   35797026  i7y8VenGMeyuABwbzvi7ZBoMWiS4dvFkWTF8y8pPy/E=
1430289   12332060  iDBwOcUciZNWa5tRV+SBYmjubvGz3DpbziTsckNjOiu=
1430290   12135232  HFvDcf9KuTnyrZIC12Fm+uTdyqR3zKt0Mp9ELQny1qc=
1430291   11512788  8jKTGUz5J8FYqarpiCkwQcBut+c9JyoNn1suDHBZUXO=
1430292    1183236  S6WJOj4SmLkCp0+GzK75unP1j44BXLV3OZMrz7o9dcS=
1430293   12273800  S+wt1G2/rkoDqPMLHcbdCAo7MsPJRLtmzFhWH655+f0=
1430294   11693378  u/AfwSkqGo0SfV1eR14w8cdcCYdG06G/RkBt5OjaVOK=
1430295   11505418  FfDDMJ+YHO48tkp3NCiQLchS3quQYpINbUELrLXc9nE=
1430296    9538360  lpVX0Lc1KtimjH44/SKjuYPSmZb4ZVNkXV9zj2scq6I=
1430297   16539632  La60C/scMI/td+04XKkN/FCIvdfveeUknaT8bpTW3A4=
1430298    6197684  zG9vdTX72T4JeVQUvpmG+1UNv6GNCOh0rzZMCutlFkO=
1430299    7181452  WPTzdb7+5DbLBIasXYpPOUuFz+e0whOVgyvqK+IbM/4=
1430300   17147430  9NebsHwJK3eDU/qZkYFbOaTa6tgX5P0jSYIqMMHbJhA=
1430301    3580162  CWY9Yb8P8tryWohoL7xTZCWt3vW/H0OvikbKV/REVe4=
1430302   11338618  D/5GDgFQnIhWPCy/dGwzAWBfzW0Bi6jsbqgm8cKWl5E=
1430303   10731414  WqzADRV/MutSUjM0FLvUbrKyqcEZDaWJX+Z6o5cmYUA=
1430304   10915308  AMIBnVUF4G5O8Y+dMkgKXo4bUjm8f4uo6gatFzUSITO=
1430305    7748968  uq2224HC0e9tTnSo9MbDsFE71oF8nat+l7qMpwhpt4S=
1430306    7061456  ZSTXD6wfHN/1qPVqMrIbwHYX5ELWlUPO3NFXCHK50Mc=
1430307   26416970  o+9gbX201ITS3MuMZYjuZUzV7sOoR57/0ttyX3eSWTA=
1430308   79633116  NZhNiXYhArpPquzrqh/kVj2IZ3QPRKm6FH90vsTlhiy=
1430309   19883370  dZ7YqVTprtTvLT4qS0YEWsn9EJahBJVQtTLKC6WaHZA=
1430310     698234  Mtmaool7T0CUyHJD112gAw6OiTl4tVSAPK4njG9B56y=

[1430311 rows x 2 columns]

In [7]:
cards = pd.read_csv('opn-rd2-acv/credit_cards.csv')
cards

          userid               credit_card
0        2579938  832299xxxxxx4902|02-2019
1        2154902  322429xxxxxx3848|05-2020
2        5578604  322429xxxxxx1293|11-2016
3        2051728  388329xxxxxx4303|09-2016
4        6216212  322421xxxxxx4238|05-2018
5        7661324  388322xxxxxx8304|09-2018
6        9554574  829092xxxxxx2938|08-2019
7       11853094  388329xxxxxx3308|09-2018
8        7965348  322429xxxxxx8232|01-2021
9        7313766  390219xxxxxx0390|09-2016
10      13391252  323809xxxxxx9200|12-2017
11      16719792  893298xxxxxx2244|02-2018
12      14188162  323809xxxxxx3409|08-2018
13      10635252  832299xxxxxx2921|05-2017
14       9344564  349394xxxxxx3242|04-2018
15      17983302  308839xxxxxx3088|02-2020
16       6171188  301433xxxxxx8033|05-2026
17      13038228  390219xxxxxx0928|12-2017
18      11036546  322429xxxxxx0942|09-2020
19      11746202  388322xxxxxx2408|01-2018
20       7718962  830422xxxxxx4008|01-2021
21       2110242  899949xxxxxx1223|03-2018
22      22585768  829132xxxxxx2003|02-2019
23       2479350  301433xxxxxx2383|12-2020
24      26184880  390219xxxxxx8892|09-2021
25       5670784  388322xxxxxx3309|07-2020
26      19836750  893298xxxxxx9312|12-2021
27       6515170  324380xxxxxx9391|03-2020
28      13633998  830129xxxxxx2223|05-2019
29      10151718  388322xxxxxx1309|04-2020
...          ...                       ...
38678   32757640  830129xxxxxx2301|07-2019
38679   90840718  392843xxxxxx2203|06-2022
38680   90235154  839199xxxxxx9428|10-2022
38681   97324466  332498xxxxxx4923|12-2022
38682   95324386  839223xxxxxx2809|08-2020
38683   82057336  830129xxxxxx2804|01-2018
38684   24303182  390212xxxxxx1349|05-2021
38685   20460564  322421xxxxxx9811|06-2018
38686   89659960  893298xxxxxx3433|09-2022
38687    7135792  830129xxxxxx1201|12-2020
38688   61009112  310992xxxxxx4909|10-2019
38689  102328062  832299xxxxxx3299|12-2021
38690   25943572  393019xxxxxx1942|11-2020
38691   19684450  393019xxxxxx9310|02-2021
38692   76016846  333843xxxxxx0899|04-2020
38693   65106236  830129xxxxxx3329|09-2021
38694   33637860  322421xxxxxx8024|12-2021
38695   34412678  839199xxxxxx9993|06-2022
38696  104476192  322421xxxxxx9294|11-2021
38697   31091192  388322xxxxxx2300|07-2021
38698    2551260  391094xxxxxx4922|12-2022
38699   67258882  323809xxxxxx4209|10-2019
38700   55982416  338244xxxxxx4423|01-2022
38701  106955574  398138xxxxxx2084|03-2022
38702  111303046  323001xxxxxx2210|10-2020
38703   25879226  839199xxxxxx3838|12-2022
38704    9331492  398138xxxxxx2208|08-2019
38705    2890486  839330xxxxxx9180|08-2022
38706  107429252  899933xxxxxx2930|06-2021
38707   78930744  392843xxxxxx2933|07-2021

[38708 rows x 2 columns]

In [8]:
accounts = pd.read_csv('opn-rd2-acv/bank_accounts.csv', converters={1: str})
accounts

          userid     bank_account
0       21829134  923302000003892
1       95910542  011002023212822
2       96941876       0189303223
3       23452396    2280003199803
4       12647942  032002028484803
5       93351382    2200092211113
6       73673972  898802093909822
7       32609752    2390022092232
8       97851414  002902002222839
9       90467238       4032444322
10      97977206  230902094022823
11      72355080    2930008149920
12      37551432  002102083989804
13      13720636       0033088429
14      86870650  249202092242820
15      98834544  299202098910823
16      99017396       0809832839
17      75648794      23220002222
18      82320120       9930029218
19      13035010  090302023239802
20      80069900       2209939893
21      79283302       0419099918
22      45272194  293102009941821
23      84946572  323402029238822
24      14387884  022202023022801
25      75536478       9442848923
26      65039678       2902803242
27      51258972       0304182323
28      65632432       4440403131
29      54774376       0210320939
...          ...              ...
350811  21124958       9229398919
350812  21016390       0840329482
350813  15104348       0339924303
350814  22151644       9320233080
350815  17575470       2242100310
350816  17964646    2290022222242
350817   5940740       0299292929
350818  14445274       4200308203
350819  22412456       2209910109
350820  19877992       9220299314
350821   9393788       4092089494
350822  22844462       0912288393
350823  22632854       2999089419
350824  22851392       0912242293
350825  15526914    2890002293340
350826  15785630    2220022228894
350827  12004220  841002000192824
350828  23051132     002309802340
350829  22631226  009902029839802
350830   7921368       3232422933
350831  11367690  391302003241821
350832  23446396  884102022094820
350833  21791446    2300023189392
350834  23150896       0092428819
350835  20951636       3130002829
350836  23568930  084902023320802
350837  17207934  023102020991822
350838  23862272       0090343142
350839  23983072       3330993800
350840  13282776       0942232333

[350841 rows x 2 columns]

In [9]:
devices.device.value_counts()

OqtiOn3PQUFp/QE5HMhvVww2jndmQ7ZTKlaRqnhdqBK=    36
Uzee3tLpqvmCbggwXmjXnX+X+R3sL1XuahyZ2UFSneA=    29
Ek+CYZB5GiI2bz6r9uR+bq78vCKNT2fPW6f2gY+phWA=    29
ATfLHxh5g2BoQr4UXuJklwKdZry2xMFzh/4VTrag/d4=    23
miqxCLQbQ3nNjaVVhwpiw5EC192XPpP1q/mRiWUXULu=    22
PiHWGBqX/+Wu7KY1HzYycix0oEhea8Wr59mvizmWp68=    22
druQWDyeClNNB3JPFDgU7Ej8qLa7S1thaOh0H0onejc=    21
MqoZUhSJSzhOs2Ip1IIOBGjGf4GILeWGxZYLK8V/Clu=    21
UGeW99geT4FeSoMx225FF9uPCm3AR4fsttQzoMJjwEu=    19
J7xZYI3ddiqReLlnOiwWPJ9ENHXt4pbshjFjs8T2G7W=    19
3BKBXXst5hccCtE69zxkwf2Pu2yCPfVnZQfRL6ay7Sc=    18
3+RlPf+2ll4ionhhZNOsW3/W9fmBU1gRPyR/y5B41by=    18
qcirq49LYFZtummBYXmhHB8kXyawoNAeToAf8/1HWI8=    17
X6Fk5tLBzGEz35cN5xKtSPHzg/ID630Z9ZYjlPgDtyS=    17
tUeV/YlwszINA/UT1T2yqVDvfXrUVn3rLrjcKai9DNu=    17
J4RPR3okjZIMuBO4W6h1opv9ipNZRq8ze7wzYFPVeBE=    17
33WmTCpENu1i6Y72FbsgSb3cRxWP4aW9Yc4DB2VqRi4=    16
f0NUfrF2VjmuVuKCvr7t+7NfFfPd2zRCZBuvV3ItDCS=    16
i8WFREbQzo26MqCBFi/gXHqMyv+uRF0Wka4p+ux7Cxu=    16
+Zf74A4C6KUM4apNZYprHXRJHfE8j6y4xHFhGO14Vtu=    15
ZrQjUkFjwzZ5T4awhKjgHt1BIocaxwDRLkdpE26Maoy=    15
6YThYb3EImz51GXK3poxHfcwCa6MrLd8B2OcWNA68wE=    15
x7sfDEvxmDeJIJoFY03fbZCF4S5Vps3MXjjAb9ByFJI=    15
efaN2N1DhYfp/s3T18MGwsvoqwlhW939RsHeOIERzAK=    15
DaMKFkFx7PAsERDi2QGZsQ9oSOBYSzHyX0YWCjo4SPq=    14
Et3bwd2vR2lMsCqufubilV3dewrPxTUIJigPvl5Urfq=    14
fQG3QmJFSCkCLIxzo8qNd7wdGwtxqJHy2plvhWF8hv8=    14
7Vf/uD0dXm0ZQ1nEhLLRaAhrmQYrLl4cb0mN8NWUreO=    13
uP/NrK1Qxb9TF4IFOgNMMCxFnOTvPz4xBX5WsaZ3rKm=    13
AiWXHVUVOPPDfPntrU/LypxPIdCxjHmGIIJTIGKjNeq=    12
                                                ..
gIKz/Ng2mYfJ2UkoUSqJleXZiPiKm0+qtqzaFlXBwRE=     1
K4cSyWZhIbj8z7WUdUnZP/JVfui6axK0xDH6gg0iiE8=     1
0IgBdphQrFrX/7qEmxc/wu0IYmxCUPkpNoC25OSad60=     1
eaueaS/weatLkl6GqdAOMrfvhLLiE6DhFvT0BGm5THu=     1
NINr6r9EeaDJ/WUvcAE71oMLgm6AwDoFPjvbJOpbuVc=     1
yuJaOGqW91w2Jnxc36/J8F+cFQ7Xxx4FxxAOXu9q948=     1
nfrR1EI/NAKiM2dHnzTvMZu4EHFHlOS0Tsyg9LTyvMc=     1
wFkOenYhGbF4zx4bI8Dx6MKvqB7jH8Dopqn0DpPiuXW=     1
yzdcoBy6FyFm4hAdwxelB8B2yrBCFZz18WtNEoefqf8=     1
qvsNtAxHSl7l/2KWDp9ZMtTAtAkLZFG/IyAEryKNjJy=     1
92+/fr8QNiRVY+921PvhFftFeJu9HXKmDz6OzQdiIkm=     1
q23TL+rAAg8vzJAu9lYQCwBYGYx6UmjVlomgL3pkR0c=     1
J/Y66xmuqwnhnq1aWLw6qLSA7htX2B2lbdF5muQ7epc=     1
4ouPX5P9hSBDzOp1eKP0ECJSd2vyHNvOiDcZbXUKfiA=     1
WJ23jgso+24dk+qVbhCkLsnv9gAv7aUc0lp8oGVjLym=     1
eRK64LZDgTW0Mfxvqk4FZsImDYJiXWGlxXz5suYUmOS=     1
zRBdw/DBZyYfO8S9/V4y8bWzRrQboMhmozKJA/YIulW=     1
O1smyHqT5BbWI/7FXhDoT1xW+vq6Ij2GeyurzV3cODc=     1
kBJveOoWwD1//xZZVoVvxQU/aEHFsedwNtKcI4KPdic=     1
q6ddJl6llmkour70JXkbFaTALKVSJctbH+2UXDIGUS0=     1
Djj1+t2q7nA6Y+9FWA03MzBY8PvO081F7lxbdnYN5kS=     1
e2eW84SKXf2YLa+S9r8aOtid5hj4389z0sQZyvDlWKg=     1
Fz/TcC1v6qI9a5Xo6n1bYVcl7iMouXU7cbp+o2/41TK=     1
Ota7QKohalDUejtHmbFrSaZcBlN7n6fqXmJzdQSUu9g=     1
iwz78J2crDlN3DO8cdX1VFLdVxotmjnPAh39dRRzpJ8=     1
1dde8XOFsqgrSrKV3yGZOu3b3rNj9V9tq29KE7v7ycm=     1
hQBb1aQHvkJKSd6SoZwN09ja4C/7faToKHw3Va08f1q=     1
TLYpVCuK56KWQijly9vKgBDVpAjrmhwL+t7w8bd5pzA=     1
8gL9ysTkXF50Ed6cgHejR5Apn6BynDAnUxErJqv/YM4=     1
k6hapLFsillk+bslCjf5AL9ED031r/Z9W/Fb1Hu58/K=     1
Name: device, Length: 1363287, dtype: int64

In [10]:
cards.credit_card.value_counts()

388322xxxxxx2203|01-2021    5
388322xxxxxx0300|02-2021    4
388322xxxxxx9102|11-2020    4
390219xxxxxx8912|05-2021    4
301433xxxxxx9423|06-2024    4
388322xxxxxx1909|08-2020    4
323809xxxxxx0202|11-2018    4
388322xxxxxx4902|05-2021    4
388322xxxxxx9928|04-2021    4
388322xxxxxx9903|03-2021    4
832299xxxxxx3299|12-2021    3
383419xxxxxx3003|10-2018    3
383419xxxxxx4002|11-2018    3
301348xxxxxx4224|07-2021    3
388322xxxxxx2303|09-2020    3
388322xxxxxx2404|12-2017    3
322421xxxxxx9990|06-2019    3
391094xxxxxx4222|08-2021    3
388329xxxxxx2108|04-2020    3
388322xxxxxx2303|06-2020    3
391094xxxxxx1828|03-2022    3
339243xxxxxx9004|03-2019    3
323001xxxxxx0044|02-2018    3
331282xxxxxx3920|10-2020    3
839199xxxxxx9384|05-2022    3
301433xxxxxx1190|03-2024    3
391094xxxxxx1393|08-2022    3
388329xxxxxx3202|11-2019    3
301348xxxxxx2298|12-2017    3
301348xxxxxx1098|01-2020    3
                           ..
332449xxxxxx2938|03-2021    1
839328xxxxxx1932|06-2022    1
839223xxxxxx0892|08-2018    1
330929xxxxxx2332|11-2022    1
330929xxxxxx0140|01-2023    1
349391xxxxxx3421|05-2022    1
388322xxxxxx1101|12-2021    1
322429xxxxxx2849|03-2022    1
301433xxxxxx2942|02-2020    1
390219xxxxxx3321|02-2021    1
822321xxxxxx3992|06-2018    1
333230xxxxxx0338|08-2022    1
312319xxxxxx2432|01-2022    1
839224xxxxxx2224|11-2019    1
391094xxxxxx9342|04-2021    1
388322xxxxxx9101|07-2021    1
839224xxxxxx3980|04-2019    1
829438xxxxxx0443|11-2017    1
829343xxxxxx1223|06-2019    1
391094xxxxxx9134|08-2018    1
393922xxxxxx1931|10-2021    1
323001xxxxxx3492|10-2021    1
838911xxxxxx3020|08-2018    1
339243xxxxxx3200|06-2019    1
320803xxxxxx4483|05-2019    1
390212xxxxxx0024|08-2018    1
322421xxxxxx8339|06-2017    1
829999xxxxxx2804|11-2019    1
388322xxxxxx0231|04-2021    1
390219xxxxxx3193|12-2021    1
Name: credit_card, Length: 37367, dtype: int64

In [11]:
accounts.bank_account.value_counts()

0934222000         89
0931388844         23
8330981244         18
9930843399         15
0039499339         13
9920214119         13
0390482908         12
2399133111         12
0910438982         10
2030001902343      10
0229049139         10
8228224002          9
2390000499991       9
0220899999993       9
0830939392          9
3242200921          9
2230024229820       9
299202022933824     9
291902029230822     9
8298040929          9
2900020392429       8
3010222998          8
9323029029          8
2242100310          7
242302023229820     7
2810921294          7
2220004333319       7
9200220811          7
2280029922804       7
9300013999          7
                   ..
9028093832          1
4118939142          1
2982233184          1
8922280932          1
9498004891          1
032249983           1
1000098229204       1
3292343348          1
0939992280          1
2910022009          1
0222991929          1
0429843914          1
233402000382802     1
9920430022          1
0292138448          1
8998098818          1
888802024413822     1
8890323328          1
2380931941          1
2980331433          1
0428190494          1
3940923923          1
088902004018823     1
214302020413829     1
2840008949349       1
9230449202          1
382302023330829     1
432493083900        1
4910183329          1
281202099829829     1
Name: bank_account, Length: 328543, dtype: int64

In [12]:
def update(v1, v2):
    l1 = list(g[v1])
    l2 = list(g[v2])
    for v in l1:
#         for u in l2:
#             if u not in g[v]:
#                 g[v][u] = g[v][v1] + [v1, v2] + g[v2][u]
#                 g[u][v] = g[u][v2] + [v2, v1] + g[v1][v]
#             elif len(g[v][u]) > len(g[v][v1]) + 2 + len(g[v2][u]):
#                 g[v][u] = g[v][v1] + [v1, v2] + g[v2][u]
#                 g[u][v] = g[u][v2] + [v2, v1] + g[v1][v]
        if v2 not in g[v]:
            g[v][v2] = g[v][v1] + [v1]
            g[v2][v] = [v1] + g[v1][v]
        elif len(g[v][v2]) > len(g[v][v1]) + 1:
            g[v][v2] = g[v][v1] + [v1]
            g[v2][v] = [v1] + g[v1][v]
    for u in l2:
        if u not in g[v1]:
            g[v1][u] = [v2] + g[v2][u]
            g[u][v1] = g[u][v2] + [v2]
        elif len(g[v1][u]) > 1 + len(g[v2][u]):
            g[v1][u] = [v2] + g[v2][u]
            g[u][v1] = g[u][v2] + [v2]
    g[v1][v2] = []
    g[v2][v1] = []

In [13]:
%%time
from collections import defaultdict, deque
g = defaultdict(set)
for idx, ut in cards.iterrows():
    if idx % 100000 == 0:
        print(idx)
    u, t = ut
    t = 'credit_card:' + t
    g[u].add(t)
    g[t].add(u)

0
CPU times: user 3.66 s, sys: 45.9 ms, total: 3.71 s
Wall time: 3.72 s

In [14]:
%%time
for idx, ut in accounts.iterrows():
    if idx % 100000 == 0:
        print(idx)
    u, t = ut
    t = 'bank_account:' + str(t)
    g[u].add(t)
    g[t].add(u)

0
100000
200000
300000
CPU times: user 34.5 s, sys: 418 ms, total: 34.9 s
Wall time: 35.1 s

In [15]:
%%time
for idx, ud in devices.iterrows():
    if idx % 100000 == 0:
        print(idx)
    u, t = ud
    t = 'device:' + t
    g[u].add(t)
    g[t].add(u)

0
100000
200000
300000
400000
500000
600000
700000
800000
900000
1000000
1100000
1200000
1300000
1400000
CPU times: user 2min 16s, sys: 1.59 s, total: 2min 18s
Wall time: 2min 18s

In [16]:
from collections import deque

def DFS(buyer, seller):
    visit = set()
    queue = [[buyer]]
    
    while queue:
        path = queue.pop(0)
        v = path[-1]
        if v == seller:
            return path[:-1]
        elif v not in visit:
            for u in g[v]:
                new_path = list(path)
                new_path.append(u)
                queue.append(new_path)
            visit.add(v)
    return []

In [17]:
%%time

with open('out2.csv', 'w') as f:
    f.write('orderid,is_fraud\n')
    for idx, order in orders.iterrows():
        if idx % 100000 == 0:
            print(idx)
        oid, buyer, seller = order
        #print(oid, buyer, seller)
        if buyer == seller:
            f.write(str(oid) + ',' + str(buyer) + '\n')
            continue
        if buyer in g and seller in g:
            res = DFS(buyer, seller)
            if res:
                f.write(str(oid) + ',')
                for link in res:
                    if isinstance(link, str):
                        f.write('"' + link + '"->')
                    else:
                        f.write(str(link) + '-')
                f.write(str(seller) + '\n')
            else:
                f.write(str(oid) + ',not fraud\n')
        else:
            f.write(str(oid) + ',not fraud\n')

0
100000
200000
300000
400000
500000
600000
CPU times: user 1min 16s, sys: 696 ms, total: 1min 17s
Wall time: 1min 17s